blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/PescadoGames/discord-rich-help.py/discussions/new?category=q-a
    about: For questions and doubts, please visit the forum.
