name: Feature Request
description: Requests for new features and requests for improvements.
labels: ["enhancement"]
title: "[Feat]: "
body:
  - type: textarea
    attributes:
      label: Request Details
      description: Please be specific.
    validations:
      required: true
