name: Feature Request
description:
labels: ["enhancement"]
title: "[Feat]: "
body:
  - type: textarea
    attributes:
      label: Request Details
      description: Please be specific.
    validations:
      required: true
