name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.x
    - name: Install dependencies
      run: python -m pip install poetry
    - name: Register token
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry config pypi-token.pypi ${{ env.PYPI_TOKEN }}
    - name: Release to PyPI
      if: startsWith(${{ github.ref_name }}, 'release/')
      run: poetry publish --build
