name: Test

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.x
    - name: Install dependencies
      run: python -m pip install .[test]
    - name: Run Flake8
      run: pflake8 ./discord_rich_help/

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.x
    - name: Install dependencies
      run: python -m pip install .[test]
    - name: Run mypy
      run: mypy ./discord_rich_help/

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.x
    - name: Install dependencies
      run: python -m pip install .[test]
    - name: Run pytest
      run: pytest ./tests
